name: animated_floating_button_pro
description: A new Flutter package that provide AnimatedFloatingButton for that provide pretty animation for FloatingActionButton.
version: 0.0.2
homepage: https://github.com/yazeed-mohammad/animatedFloatingButton

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: